version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql:db
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
  php:
    build: ./php 
    volumes:
      - ./html:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.5.3.1-1
    ports:
      - "8080:8080"
    links:
      - mysql:db